stages:
  - quality
  - deploy
.tags-default: &tags-default
  tags:
    - devops

.only-default: &only-default
  only:
    - master

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.init_ssh_stg: &init_ssh_stg |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY_STG" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.init_ssh_prod: &init_ssh_prod |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
PHP Stan:
  image: lyni/phpqa:7.4-latest
  stage: quality
  <<: *tags-default
  script:
    - git fetch origin
    - git branch
    - composer i
    - phpstan analyse core modules --level 1

PHP Security:
  image: lyni/phpqa:7.4-latest
  stage: quality
  <<: *tags-default
  script:
    - git fetch origin
    - git branch
    - composer i
    - local-php-security-checker

PHP Copy/Paste Detector:
  image: lyni/phpqa:7.4-latest
  stage: quality
  <<: *tags-default
  script:
    - git fetch origin
    - git branch
    - composer i
    - phpcpd core modules

PHP Magic Number:
  image: lyni/phpqa:7.4-latest
  stage: quality
  <<: *tags-default
  script:
    - git fetch origin
    - git branch
    - composer i
    - phpmnd core modules --ignore-numbers=2,-1 --ignore-funcs=round,sleep --exclude=tests --progress \
      --extensions=default_parameter,-return,argument

dev:
  image: lyni/php-cd:7.4-latest
  stage: deploy
  <<: *tags-default
  script:
    - *init_ssh
    - /composer/vendor/bin/envoy run deploy --server=dev --npm=prod
  only:
    - dev
  when: manual

staging:
  image: lyni/php-cd:7.4-latest
  stage: deploy
  <<: *tags-default
  script:
    - *init_ssh_stg
    - /composer/vendor/bin/envoy run deploy --server=staging --npm=prod
  only:
    - staging
  when: manual

honban:
  image: lyni/php-cd:7.4-latest
  stage: deploy
  <<: *tags-default
  script:
    - *init_ssh_prod
    - /composer/vendor/bin/envoy run deploy --server=prod --npm=prod
  when: manual
  only:
    - master
